title: "Mi Sitio Jekyll Personalizado"
description: "Documentaci칩n y ejemplos para mi sitio Jekyll personalizado."
baseurl: "/docs" # solo si el sitio est치 en una subcarpeta
url: "https://tusitio.github.io" # la URL de tu sitio
theme: null
markdown: kramdown

# Configuraci칩n del sitio
include:
  - _pages
  - _posts

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Configuraci칩n de Sass
sass:
  style: compressed
